### PR TITLE
Website

### LINKED ISSUE #5: New Website
Hello:)
I am a front end developer, and I would like to contribute by creating a website for this extension.

I can create a website with different technologies.

### PR DESCRIPTION
**Pull request by Bashamega**
closes #5 
I have created a simple static website for the chrome extension

### CODE REVIEW

**Comment by Bashamega** [comment]
@THammami01

**Comment by THammami01** [comment]
Hi @Bashamega,
I'm sorry for the wait; I couldn't answer only now.
Could you please provide a screenshot of the website in a comment?

**Comment by Bashamega** [comment]
> Hi @Bashamega, I'm sorry for the wait; I couldn't answer only now. Could you please provide a screenshot of the website in a comment?

This is a screenshot
image
If you have another theme in mind or colors or a change request, please tell me.

**Comment by THammami01** [comment]
This is how it looks on mobile. :D
It would be great to make it responsive and look nice on small screens.
I'll merge your pull request once that's done!

**Comment by Bashamega** [comment]
Hello @THammami01 :)
I have added the responsive design.
Note: Merge this PR in a separate branch, because I have removed the code for the extension in the PR.

**Comment by Bashamega** [comment]
@THammami01

**Pull request closed without merging**
